return {
	-- --	dash board
	-- {
	-- 	"goolord/alpha-nvim",
	-- 	dependencies = {
	-- 		"nvim-tree/nvim-web-devicons",
	-- 	},
	--
	-- 	config = function()
	-- 		local alpha = require("alpha")
	-- 		local dashboard = require("alpha.themes.dashboard")
	-- 		dashboard.section.header.val = {
	-- 			"                                                     ",
	-- 			"  ███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗ ",
	-- 			"  ████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║ ",
	-- 			"  ██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║ ",
	-- 			"  ██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║ ",
	-- 			"  ██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║ ",
	-- 			"  ╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝ ",
	-- 			"                                                     ",
	-- 		}
	--
	-- 		dashboard.section.buttons.val = {
	-- 			dashboard.button("e", "  New file", ":ene <BAR> startinsert <CR>"),
	-- 			dashboard.button("f", "  Find file", ":cd $HOME/Workspace | Telescope find_files<CR>"),
	-- 			dashboard.button("r", "  Recent", ":Telescope oldfiles<CR>"),
	-- 			dashboard.button("s", "  Settings", ":e $MYVIMRC | :cd %:p:h | split . | wincmd k | pwd<CR>"),
	-- 			dashboard.button("q", "󰿅  Quit", ":qa<CR>"),
	-- 		}
	-- 		alpha.setup(dashboard.opts)
	-- 		vim.cmd([[
	-- 		 autocmd FileType alpha setlocal nofoldenable
	-- 		]])
	-- 	end,
	-- },
	--
	--
	-- ----------------------------------------
	-- Supermaven
	--
	-- {
	-- 	"supermaven-inc/supermaven-nvim",
	-- 	config = function()
	-- 		require("supermaven-nvim").setup({})
	-- 	end,
	-- },
	--
	-- ----------------------------------------
	-- Codeium
	-- {
	-- "Exafunction/codeium.nvim",
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- 	"hrsh7th/nvim-cmp",
	-- },
	-- config = function()
	-- 	require("codeium").setup({
	-- 		enable_cmp_source = false,
	-- 		virtual_text = {
	-- 			enabled = true,
	-- 			manual = false,
	-- 			filetypes = {},
	-- 			default_filetype_enabled = true,
	-- 			idle_delay = 75,
	-- 			virtual_text_priority = 65535,
	-- 			map_keys = true,
	-- 			accept_fallback = nil,
	-- 			key_bindings = {
	-- 				accept = "<Tab>",
	-- 				accept_word = false,
	-- 				accept_line = false,
	-- 				clear = false,
	-- 			},
	-- 		},
	-- 	})
	-- end,
	-- },
	-- ----------------------------------------
	-- {
	-- "folke/flash.nvim",
	-- event = "VeryLazy",
	-- ---@type Flash.Config
	-- opts = {},
	--  -- stylua: ignore
	--  keys = {
	--    { "s", mode = { "n", "x", "o" }, function() require("flash").jump() end, desc = "Flash" },
	--    { "S", mode = { "n", "x", "o" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
	--    { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
	--    { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
	--    { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
	--  },
	-- },
	-- ----------------------------------------
}
