
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg1)\
$os\
$username\
[](bg:color_orange fg:color_bg1)\
$directory\
[](fg:color_orange bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:color_aqua)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_aqua bg:color_blue)\
$docker_context\
[](fg:color_blue bg:color_yellow)\
$time\
[ ](fg:color_yellow)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'  # Gruvbox light foreground
color_bg1 = '#3c3836'  # Gruvbox dark background
color_bg3 = '#665c54'  # Gruvbox gray background
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = true
style = "bg:color_bg1 fg:color_fg0"

[username]
show_always = true
style_user = "bg:color_bg1 fg:color_fg0"
style_root = "bg:color_bg1 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg1 bg:color_orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_bg1 bg:color_green)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_bg1 bg:color_green)]($style)'

[nodejs]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_bg1 bg:color_aqua)]($style)'

[c]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_bg1 bg:color_aqua)]($style)'

[rust]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_bg1 bg:color_aqua)]($style)'

[golang]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_bg1 bg:color_aqua)]($style)'

[php]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_bg1 bg:color_aqua)]($style)'

[java]
symbol = " "
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_bg1 bg:color_aqua)]($style)'

[kotlin]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_bg1 bg:color_aqua)]($style)'

[haskell]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_bg1 bg:color_aqua)]($style)'

[python]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_bg1 bg:color_aqua)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_aqua bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%I:%M"
style = "bg:color_orange"
format = '[[  $time ](fg:color_bg1 bg:color_yellow)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_purple)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

