format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

# User indicator for distinguishing normal and root sessions
[custom.user_indicator]
command = "if [ $(whoami) = root ]; then echo '[ ROOT]'; else echo '[ USER]'; fi"
when = "true"
style = "bold"
format = "[$output](fg:#fabd2f)" # Yellow (Gold) for user/root differentiation

[directory]
style = "fg:#83a598" # Aqua for directory

[character]
success_symbol = "[❯](fg:#ebdbb2)"
error_symbol = "[❯](fg:#fb4934)" # Red for errors
vimcmd_symbol = "[❮](fg:#fe8019)" # Orange for vim commands

[git_branch]
format = "[$branch]($style)"
style = "fg:#8ec07c" # Green for branch

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](fg:#fb4934) ($ahead_behind$stashed)]($style)"
style = "fg:#d3869b" # Purple for git status
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)](fg:#83a598)\) '
style = "fg:#83a598" # Aqua for git state

[cmd_duration]
format = "[$duration](fg:#b8bb26) " # Green for command duration
style = "fg:#b8bb26"

[python]
format = "[$virtualenv](fg:#fabd2f) " # Yellow for Python virtualenv
style = "fg:#fabd2f"
