format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

# User indicator for distinguishing normal and root sessions
[custom.user_indicator]
command = "if [ $(whoami) = root ]; then echo '[ ROOT]'; else echo '[ USER]'; fi"
when = "true"
style = "bold"
format = "[$output](fg:#ffeb95)" # Gold for user/root differentiation

[directory]
style = "fg:#82aaff" # Light blue for directory

[character]
success_symbol = "[❯](fg:#cfcfcf)"
error_symbol = "[❯](fg:#e57373)" # Light red for errors
vimcmd_symbol = "[❮](fg:#f78c6c)" # Light orange for vim commands

[git_branch]
format = "[$branch]($style)"
style = "fg:#c0caf5" # Soft cyan for branch

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](fg:#f7768e) ($ahead_behind$stashed)]($style)"
style = "fg:#b4befe" # Soft purple for git status
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)](fg:#7aa2f7)\) '
style = "fg:#7aa2f7" # Light blue for git state

[cmd_duration]
format = "[$duration](fg:#9ece6a) " # Green for command duration
style = "fg:#9ece6a"

[python]
format = "[$virtualenv](fg:#f9e2af) " # Light yellow for python virtualenv
style = "fg:#f9e2af"
